version: "3"

services:
  mongodb:
    image: mongo:3.2.9
    networks:
      - imac
    volumes:
      - imac:/data/db

  imac:
    image: imac:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOST=mongodb
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - imac

networks:
  imac: {}

volumes:
  imac: {}
